"""Allow alphanumeric hex codes

Revision ID: 30c5ced21b9a
Revises: a1bb1583401b
Create Date: 2023-04-04 10:13:50.397717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30c5ced21b9a'
down_revision = 'a1bb1583401b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fractal', schema=None) as batch_op:
        batch_op.alter_column('hex_value',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=6),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fractal', schema=None) as batch_op:
        batch_op.alter_column('hex_value',
               existing_type=sa.String(length=6),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
