"""add fractal model

Revision ID: a1bb1583401b
Revises: 46f3980cb799
Create Date: 2023-04-04 06:43:51.517238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1bb1583401b'
down_revision = '46f3980cb799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fractal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fractal_type', sa.Enum('mandel', 'julia', name='myenum'), nullable=True),
    sa.Column('hex_value', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hex_value')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fractal')
    # ### end Alembic commands ###
